/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReportsRouteImport } from './routes/_layout/reports'
import { Route as LayoutPrescriptionsRouteImport } from './routes/_layout/prescriptions'
import { Route as LayoutPatientsRouteImport } from './routes/_layout/patients'
import { Route as LayoutOnsiteRouteImport } from './routes/_layout/onsite'
import { Route as LayoutMedicinesRouteImport } from './routes/_layout/medicines'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFollowupsRouteImport } from './routes/_layout/followups'
import { Route as LayoutFinanceRouteImport } from './routes/_layout/finance'
import { Route as LayoutCoreSettingsRouteImport } from './routes/_layout/core-settings'
import { Route as LayoutCasesRouteImport } from './routes/_layout/cases'
import { Route as LayoutAvailabilityRouteImport } from './routes/_layout/availability'
import { Route as LayoutAppointmentsRouteImport } from './routes/_layout/appointments'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutWebContentIndexRouteImport } from './routes/_layout/web-content/index'
import { Route as LayoutWebContentTestimonialsRouteImport } from './routes/_layout/web-content/testimonials'
import { Route as LayoutWebContentServicesRouteImport } from './routes/_layout/web-content/services'
import { Route as LayoutWebContentHeroSectionRouteImport } from './routes/_layout/web-content/hero-section'
import { Route as LayoutWebContentContactInfoRouteImport } from './routes/_layout/web-content/contact-info'
import { Route as LayoutWebContentAboutDoctorRouteImport } from './routes/_layout/web-content/about-doctor'
import { Route as LayoutFinanceCashBookIdRouteImport } from './routes/_layout/finance.$cashBookId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsRoute = LayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrescriptionsRoute = LayoutPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsRoute = LayoutPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOnsiteRoute = LayoutOnsiteRouteImport.update({
  id: '/onsite',
  path: '/onsite',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMedicinesRoute = LayoutMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFollowupsRoute = LayoutFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFinanceRoute = LayoutFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoreSettingsRoute = LayoutCoreSettingsRouteImport.update({
  id: '/core-settings',
  path: '/core-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasesRoute = LayoutCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAvailabilityRoute = LayoutAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppointmentsRoute = LayoutAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWebContentIndexRoute = LayoutWebContentIndexRouteImport.update({
  id: '/web-content/',
  path: '/web-content/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWebContentTestimonialsRoute =
  LayoutWebContentTestimonialsRouteImport.update({
    id: '/web-content/testimonials',
    path: '/web-content/testimonials',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutWebContentServicesRoute =
  LayoutWebContentServicesRouteImport.update({
    id: '/web-content/services',
    path: '/web-content/services',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutWebContentHeroSectionRoute =
  LayoutWebContentHeroSectionRouteImport.update({
    id: '/web-content/hero-section',
    path: '/web-content/hero-section',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutWebContentContactInfoRoute =
  LayoutWebContentContactInfoRouteImport.update({
    id: '/web-content/contact-info',
    path: '/web-content/contact-info',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutWebContentAboutDoctorRoute =
  LayoutWebContentAboutDoctorRouteImport.update({
    id: '/web-content/about-doctor',
    path: '/web-content/about-doctor',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFinanceCashBookIdRoute = LayoutFinanceCashBookIdRouteImport.update({
  id: '/$cashBookId',
  path: '/$cashBookId',
  getParentRoute: () => LayoutFinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/appointments': typeof LayoutAppointmentsRoute
  '/availability': typeof LayoutAvailabilityRoute
  '/cases': typeof LayoutCasesRoute
  '/core-settings': typeof LayoutCoreSettingsRoute
  '/finance': typeof LayoutFinanceRouteWithChildren
  '/followups': typeof LayoutFollowupsRoute
  '/items': typeof LayoutItemsRoute
  '/medicines': typeof LayoutMedicinesRoute
  '/onsite': typeof LayoutOnsiteRoute
  '/patients': typeof LayoutPatientsRoute
  '/prescriptions': typeof LayoutPrescriptionsRoute
  '/reports': typeof LayoutReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/finance/$cashBookId': typeof LayoutFinanceCashBookIdRoute
  '/web-content/about-doctor': typeof LayoutWebContentAboutDoctorRoute
  '/web-content/contact-info': typeof LayoutWebContentContactInfoRoute
  '/web-content/hero-section': typeof LayoutWebContentHeroSectionRoute
  '/web-content/services': typeof LayoutWebContentServicesRoute
  '/web-content/testimonials': typeof LayoutWebContentTestimonialsRoute
  '/web-content': typeof LayoutWebContentIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/appointments': typeof LayoutAppointmentsRoute
  '/availability': typeof LayoutAvailabilityRoute
  '/cases': typeof LayoutCasesRoute
  '/core-settings': typeof LayoutCoreSettingsRoute
  '/finance': typeof LayoutFinanceRouteWithChildren
  '/followups': typeof LayoutFollowupsRoute
  '/items': typeof LayoutItemsRoute
  '/medicines': typeof LayoutMedicinesRoute
  '/onsite': typeof LayoutOnsiteRoute
  '/patients': typeof LayoutPatientsRoute
  '/prescriptions': typeof LayoutPrescriptionsRoute
  '/reports': typeof LayoutReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/finance/$cashBookId': typeof LayoutFinanceCashBookIdRoute
  '/web-content/about-doctor': typeof LayoutWebContentAboutDoctorRoute
  '/web-content/contact-info': typeof LayoutWebContentContactInfoRoute
  '/web-content/hero-section': typeof LayoutWebContentHeroSectionRoute
  '/web-content/services': typeof LayoutWebContentServicesRoute
  '/web-content/testimonials': typeof LayoutWebContentTestimonialsRoute
  '/web-content': typeof LayoutWebContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/appointments': typeof LayoutAppointmentsRoute
  '/_layout/availability': typeof LayoutAvailabilityRoute
  '/_layout/cases': typeof LayoutCasesRoute
  '/_layout/core-settings': typeof LayoutCoreSettingsRoute
  '/_layout/finance': typeof LayoutFinanceRouteWithChildren
  '/_layout/followups': typeof LayoutFollowupsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/medicines': typeof LayoutMedicinesRoute
  '/_layout/onsite': typeof LayoutOnsiteRoute
  '/_layout/patients': typeof LayoutPatientsRoute
  '/_layout/prescriptions': typeof LayoutPrescriptionsRoute
  '/_layout/reports': typeof LayoutReportsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/finance/$cashBookId': typeof LayoutFinanceCashBookIdRoute
  '/_layout/web-content/about-doctor': typeof LayoutWebContentAboutDoctorRoute
  '/_layout/web-content/contact-info': typeof LayoutWebContentContactInfoRoute
  '/_layout/web-content/hero-section': typeof LayoutWebContentHeroSectionRoute
  '/_layout/web-content/services': typeof LayoutWebContentServicesRoute
  '/_layout/web-content/testimonials': typeof LayoutWebContentTestimonialsRoute
  '/_layout/web-content/': typeof LayoutWebContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/appointments'
    | '/availability'
    | '/cases'
    | '/core-settings'
    | '/finance'
    | '/followups'
    | '/items'
    | '/medicines'
    | '/onsite'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/settings'
    | '/'
    | '/finance/$cashBookId'
    | '/web-content/about-doctor'
    | '/web-content/contact-info'
    | '/web-content/hero-section'
    | '/web-content/services'
    | '/web-content/testimonials'
    | '/web-content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/appointments'
    | '/availability'
    | '/cases'
    | '/core-settings'
    | '/finance'
    | '/followups'
    | '/items'
    | '/medicines'
    | '/onsite'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/settings'
    | '/'
    | '/finance/$cashBookId'
    | '/web-content/about-doctor'
    | '/web-content/contact-info'
    | '/web-content/hero-section'
    | '/web-content/services'
    | '/web-content/testimonials'
    | '/web-content'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/appointments'
    | '/_layout/availability'
    | '/_layout/cases'
    | '/_layout/core-settings'
    | '/_layout/finance'
    | '/_layout/followups'
    | '/_layout/items'
    | '/_layout/medicines'
    | '/_layout/onsite'
    | '/_layout/patients'
    | '/_layout/prescriptions'
    | '/_layout/reports'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/finance/$cashBookId'
    | '/_layout/web-content/about-doctor'
    | '/_layout/web-content/contact-info'
    | '/_layout/web-content/hero-section'
    | '/_layout/web-content/services'
    | '/_layout/web-content/testimonials'
    | '/_layout/web-content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/prescriptions': {
      id: '/_layout/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof LayoutPrescriptionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients': {
      id: '/_layout/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof LayoutPatientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/onsite': {
      id: '/_layout/onsite'
      path: '/onsite'
      fullPath: '/onsite'
      preLoaderRoute: typeof LayoutOnsiteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/medicines': {
      id: '/_layout/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof LayoutMedicinesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/followups': {
      id: '/_layout/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof LayoutFollowupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance': {
      id: '/_layout/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof LayoutFinanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/core-settings': {
      id: '/_layout/core-settings'
      path: '/core-settings'
      fullPath: '/core-settings'
      preLoaderRoute: typeof LayoutCoreSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases': {
      id: '/_layout/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof LayoutCasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/availability': {
      id: '/_layout/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof LayoutAvailabilityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/appointments': {
      id: '/_layout/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof LayoutAppointmentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-content/': {
      id: '/_layout/web-content/'
      path: '/web-content'
      fullPath: '/web-content'
      preLoaderRoute: typeof LayoutWebContentIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-content/testimonials': {
      id: '/_layout/web-content/testimonials'
      path: '/web-content/testimonials'
      fullPath: '/web-content/testimonials'
      preLoaderRoute: typeof LayoutWebContentTestimonialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-content/services': {
      id: '/_layout/web-content/services'
      path: '/web-content/services'
      fullPath: '/web-content/services'
      preLoaderRoute: typeof LayoutWebContentServicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-content/hero-section': {
      id: '/_layout/web-content/hero-section'
      path: '/web-content/hero-section'
      fullPath: '/web-content/hero-section'
      preLoaderRoute: typeof LayoutWebContentHeroSectionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-content/contact-info': {
      id: '/_layout/web-content/contact-info'
      path: '/web-content/contact-info'
      fullPath: '/web-content/contact-info'
      preLoaderRoute: typeof LayoutWebContentContactInfoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-content/about-doctor': {
      id: '/_layout/web-content/about-doctor'
      path: '/web-content/about-doctor'
      fullPath: '/web-content/about-doctor'
      preLoaderRoute: typeof LayoutWebContentAboutDoctorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance/$cashBookId': {
      id: '/_layout/finance/$cashBookId'
      path: '/$cashBookId'
      fullPath: '/finance/$cashBookId'
      preLoaderRoute: typeof LayoutFinanceCashBookIdRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
  }
}

interface LayoutFinanceRouteChildren {
  LayoutFinanceCashBookIdRoute: typeof LayoutFinanceCashBookIdRoute
}

const LayoutFinanceRouteChildren: LayoutFinanceRouteChildren = {
  LayoutFinanceCashBookIdRoute: LayoutFinanceCashBookIdRoute,
}

const LayoutFinanceRouteWithChildren = LayoutFinanceRoute._addFileChildren(
  LayoutFinanceRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAppointmentsRoute: typeof LayoutAppointmentsRoute
  LayoutAvailabilityRoute: typeof LayoutAvailabilityRoute
  LayoutCasesRoute: typeof LayoutCasesRoute
  LayoutCoreSettingsRoute: typeof LayoutCoreSettingsRoute
  LayoutFinanceRoute: typeof LayoutFinanceRouteWithChildren
  LayoutFollowupsRoute: typeof LayoutFollowupsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMedicinesRoute: typeof LayoutMedicinesRoute
  LayoutOnsiteRoute: typeof LayoutOnsiteRoute
  LayoutPatientsRoute: typeof LayoutPatientsRoute
  LayoutPrescriptionsRoute: typeof LayoutPrescriptionsRoute
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutWebContentAboutDoctorRoute: typeof LayoutWebContentAboutDoctorRoute
  LayoutWebContentContactInfoRoute: typeof LayoutWebContentContactInfoRoute
  LayoutWebContentHeroSectionRoute: typeof LayoutWebContentHeroSectionRoute
  LayoutWebContentServicesRoute: typeof LayoutWebContentServicesRoute
  LayoutWebContentTestimonialsRoute: typeof LayoutWebContentTestimonialsRoute
  LayoutWebContentIndexRoute: typeof LayoutWebContentIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAppointmentsRoute: LayoutAppointmentsRoute,
  LayoutAvailabilityRoute: LayoutAvailabilityRoute,
  LayoutCasesRoute: LayoutCasesRoute,
  LayoutCoreSettingsRoute: LayoutCoreSettingsRoute,
  LayoutFinanceRoute: LayoutFinanceRouteWithChildren,
  LayoutFollowupsRoute: LayoutFollowupsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMedicinesRoute: LayoutMedicinesRoute,
  LayoutOnsiteRoute: LayoutOnsiteRoute,
  LayoutPatientsRoute: LayoutPatientsRoute,
  LayoutPrescriptionsRoute: LayoutPrescriptionsRoute,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutWebContentAboutDoctorRoute: LayoutWebContentAboutDoctorRoute,
  LayoutWebContentContactInfoRoute: LayoutWebContentContactInfoRoute,
  LayoutWebContentHeroSectionRoute: LayoutWebContentHeroSectionRoute,
  LayoutWebContentServicesRoute: LayoutWebContentServicesRoute,
  LayoutWebContentTestimonialsRoute: LayoutWebContentTestimonialsRoute,
  LayoutWebContentIndexRoute: LayoutWebContentIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
