// This file is auto-generated by @hey-api/openapi-ts
export { ApiError } from "./core/ApiError";
export { CancelablePromise, CancelError } from "./core/CancelablePromise";
export { OpenAPI, type OpenAPIConfig } from "./core/OpenAPI";
export * from "./sdk.gen";
export * from "./types.gen";
// Temporary exports until SDK is regenerated
export {
  PatientsService,
  type PatientPublic,
  type PatientsPublic,
  type PatientCreate,
  type PatientUpdate,
} from "./PatientsService";
export {
  AppointmentsService,
  type AppointmentPublic,
  type AppointmentsPublic,
  type AppointmentCreate,
  type AppointmentUpdate,
  type AppointmentStatus,
  type AvailabilityValidationResponse,
  type PatientBookAppointmentData,
} from "./AppointmentsService";
export {
  CasesService,
  type PatientCasePublic,
  type CasesPublic,
  type CaseCreate,
  type CaseUpdate,
} from "./CasesService";
export {
  PrescriptionsService,
  type PrescriptionPublic,
  type PrescriptionsPublic,
  type PrescriptionCreate,
  type PrescriptionUpdate,
  type PrescriptionType,
  type PrescriptionMedicineCreate,
} from "./PrescriptionsService";
export {
  MedicinesService,
  type MedicineMasterPublic,
  type DoctorMedicineStockPublic,
  type MedicinesPublic,
  type MedicinesStockPublic,
  type DoctorMedicineStockCreate,
  type DoctorMedicineStockUpdate,
} from "./MedicinesService";
export {
  FollowupsService,
  type FollowUpPublic,
  type FollowUpsPublic,
  type FollowUpCreate,
  type FollowUpUpdate,
} from "./FollowupsService";
export { ReportsService } from "./ReportsService";
export {
  DoctorAvailabilityService,
  type DoctorAvailabilityPublic,
  type DoctorAvailabilitiesPublic,
  type DoctorScheduleResponse,
  type DoctorScheduleWithPatientInfo,
  type AvailableSlotCheck,
  type DayOfWeek,
} from "./DoctorAvailabilityService";
export {
  DoctorPreferencesService,
  type DoctorField,
  type InitializeResponse,
  type ToggleFieldResponse,
  type AddCustomFieldRequest,
  type AddCustomFieldResponse,
  type DeleteFieldResponse,
} from "./DoctorPreferencesService";
export {
  DoctorStatisticsService,
  type DoctorStats,
} from "./DoctorStatisticsService";
export {
  WebContentService,
  type HeroSectionCreate,
  type HeroSectionUpdate,
  type HeroSectionResponse,
  type AboutDoctorCreate,
  type AboutDoctorUpdate,
  type AboutDoctorResponse,
  type ServicesAndTreatmentsCreate,
  type ServicesAndTreatmentsUpdate,
  type ServicesAndTreatmentsResponse,
  type PatientSuccessStoriesCreate,
  type PatientSuccessStoriesUpdate,
  type PatientSuccessStoriesResponse,
  type ContactInformationCreate,
  type ContactInformationUpdate,
  type ContactInformationResponse,
  type Credential,
  type Qualification,
  type Specialization,
  type Service,
  type Testimonial,
} from "./WebContentService";
